name: Deploy

on:
  push:
    branches: [ staging, production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Forge
      env:
        FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
      run: |
        if [[ $GITHUB_REF == "refs/heads/production" ]]; then
          curl -X POST ${{ secrets.FORGE_PRODUCTION_DEPLOY_URL }}
        elif [[ $GITHUB_REF == "refs/heads/staging" ]]; then
          curl -X POST ${{ secrets.FORGE_STAGING_DEPLOY_URL }}
        fi