name: Deploy

on:
  push:
    branches: [ main, production ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        
      - name: Check PHP syntax
        run: find . -type f -name '*.php' -print0 | xargs -0 -n1 php -l